### ISSUE TITLE
Index-out-of-range may occur in job's `sample_id` property

### ISSUE THREAD

**Issue by yankovs** [danielplohmann/mcrit#56]
Hey! :)

I've recently updated to current MCRIT/web and noticed I get a crash on basically every family I try to press on in the families view. The traceback is as follows:

```console
[2023-12-12 16:39:05,607] ERROR in app: Exception on /explore/families/5 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/mcritweb/mcritweb/views/utility.py", line 39, in wrapped_view
    return view(**kwargs)
  File "/opt/mcritweb/mcritweb/views/authentication.py", line 204, in wrapped_view
    return view(**kwargs)
  File "/opt/mcritweb/mcritweb/views/explore.py", line 213, in family_by_id
    job_collection.filterToSampleIds([s.sample_id for s in samples])
  File "/usr/local/lib/python3.8/dist-packages/mcrit/queue/JobCollection.py", line 36, in filterToSampleIds
    if job.sample_id in sample_ids:
  File "/usr/local/lib/python3.8/dist-packages/mcrit/queue/LocalQueue.py", line 137, in sample_id
    return int(self.arguments[0][0])
IndexError: list index out of **range**
```

After a bit of code reading it seems like the issue is that when trying to get the samples in a family for some reason it tries to get the sample_id via `getUniqueBlocks` even though this is not the case.

Edit: the same behavior was observed in two other spots. (1) When pressing Explore -> samples, (2) Data -> Jobs/Results -> Blocks

**Comment by danielplohmann** [comment]
Hi!

Ohh, that was a tough one lol, I think I just figured out how this can happen. 
Somehow there has to be a job for a family with zero samples - the only way this can occur is when the `getUniqueBlocks` was started for Unnamed (family_id: 0) when there were no samples for it.
I'll push a fix in the next minutes after verifying that it covers all cases I can think of.
