### ISSUE TITLE
KeyError on import

### ISSUE THREAD

**Issue by malwarefrank** [danielplohmann/mcrit#64]
I am receiving the following error when attempting to import the `MSVC/x86/mcrit/2003_Express_x86.mcrit` file from the mcrit-data repo:

```
INFO:mcrit.index.MinHashIndex:Family remapping created: 1 families, 1 samples.
2024-02-09 23:46:06 [FALCON] [ERROR] POST /import => Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "/opt/mcrit/mcrit/server/utils.py", line 51, in wrapper
    func(*args, **kwargs)
  File "/opt/mcrit/mcrit/server/StatusResource.py", line 73, in on_post_import
    import_report = self.index.addImportData(import_data)
  File "/opt/mcrit/mcrit/index/MinHashIndex.py", line 220, in addImportData
    sample_entry.family_id = family_id_remapping[sample_entry.family_id]
KeyError: 0
```
I am running docker-mcrit that is using mcrit v1.3.4.  I am initiating the import using the command-line client.

**Comment by malwarefrank** [comment]
File `MSVC/x86/mcrit/VC6_Express_x86.mcrit` is causing the same error when I try to import it.

**Comment by danielplohmann** [comment]
thanks for the notice. 
I think that happened because I had a similar issue before when MSVC was `"family_id": 0"` and manually changed it in the file, but only on one instead of the two necessary locations. Fixed now!
