### ISSUE TITLE
Exception on POST /query/function

### ISSUE THREAD

**Issue by malwarefrank** [danielplohmann/mcrit#66]
I am unsure if this indicates an error with the IDA script, the mcrit service, or smda.  I am using the ida_mcrit.py in IDA via `File->Script File...` while I have a binary open in IDA.  Within the mcrit window, I click on the fingerprint icon (Convert this IDB to a SMDA...), then click on the Upload icon (Reparse and upload the SMDA report...).  I see a Python exception within the IDA console Output window and I see an exception in the mcrit logs (using docker-mcrit and docker compose).

The following is the exception I see in the mcrit-server log:
```
2024-02-14 21:51:31 [FALCON] [ERROR] POST /query/function => Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "/opt/mcrit/mcrit/server/utils.py", line 51, in wrapper
    func(*args, **kwargs)
  File "/opt/mcrit/mcrit/server/QueryResource.py", line 85, in on_post_query_smda_function
    summary = self.index.getMatchesForSmdaFunction(smda_report, **parameters)
  File "/opt/mcrit/mcrit/index/MinHashIndex.py", line 340, in getMatchesForSmdaFunction
    match_report = matcher.getMatchesForSmdaFunction(smda_report)
  File "/opt/mcrit/mcrit/matchers/MatcherInterface.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/opt/mcrit/mcrit/matchers/MatcherQueryFUnction.py", line 35, in getMatchesForSmdaFunction
    function_entry = FunctionEntry(self._sample_entry, smda_function, -1, minhash)
  File "/opt/mcrit/mcrit/storage/FunctionEntry.py", line 59, in __init__
    self.xcfg = smda_function.toDict()
  File "/usr/local/lib/python3.8/dist-packages/smda/common/SmdaFunction.py", line 257, in toDict
    "nesting_depth": self.nesting_depth,
AttributeError: 'SmdaFunction' object has no attribute 'nesting_depth'
```

I took a quick look at smda/common/SmdaFunction.py and it looks like the `fromDict()` function will only assign nesting_depth if a version is given.  I do not know the code well enough to be sure if this is the cause of the issue, but if so then you might just need to move the `else` statement on line 235 out one nesting layer to be the else for the `if version and re.match...` statement.

**Comment by danielplohmann** [comment]
Ah, I think that's actually related to some backward compatibility changes I had introduced lately and the MCRIT IDA plugin producing a version string that's not just dotted decimals...
So in a way, it's a combined problem. :)

Yeah, you are absolutely right about the position in the code where this issue occurs and the fix, that is fixed in the SMDA version I'm about to push.

Sorry, that you need to endure all this issues. :disappointed:
