### ISSUE TITLE
Cross compare broken

### ISSUE THREAD

**Issue by sebdraven** [danielplohmann/mcrit#75]
when I use the cross compare

`mcritweb      | [2024-05-30 07:49:34,433] ERROR in app: Exception on /data/jobs/66582cf4d8e38bfb930fc16b [GET]
mcritweb      | Traceback (most recent call last):
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2529, in wsgi_app
mcritweb      |     response = self.full_dispatch_request()
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1825, in full_dispatch_request
mcritweb      |     rv = self.handle_user_exception(e)
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1823, in full_dispatch_request
mcritweb      |     rv = self.dispatch_request()
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
mcritweb      |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
mcritweb      |   File "/opt/mcritweb/mcritweb/views/utility.py", line 40, in wrapped_view
mcritweb      |     return view(**kwargs)
mcritweb      |   File "/opt/mcritweb/mcritweb/views/authentication.py", line 204, in wrapped_view
mcritweb      |     return view(**kwargs)
mcritweb      |   File "/opt/mcritweb/mcritweb/views/data.py", line 754, in job_by_id
mcritweb      |     return render_template('job_overview.html', job_info=job_info, auto_refresh=auto_refresh, child_jobs=child_jobs)
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 147, in render_template
mcritweb      |     return _render(app, template, context)
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 130, in _render
mcritweb      |     rv = template.render(context)
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1304, in render
mcritweb      |     self.environment.handle_exception()
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 939, in handle_exception
mcritweb      |     raise rewrite_traceback_stack(source=source)
mcritweb      |   File "/opt/mcritweb/mcritweb/templates/job_overview.html", line 5, in top-level template code
mcritweb      |     {% extends 'base.html' %}
mcritweb      |   File "/opt/mcritweb/mcritweb/templates/base.html", line 146, in top-level template code
mcritweb      |     {% block content %}{% endblock %}
mcritweb      |   File "/opt/mcritweb/mcritweb/templates/job_overview.html", line 24, in block 'content'
mcritweb      |     {{ job_table(child_jobs) }}
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 782, in _invoke
mcritweb      |     rv = self._func(*arguments)
mcritweb      |   File "/opt/mcritweb/mcritweb/templates/table/table.html", line 35, in template
mcritweb      |     {{ _table_base(jobs, job_header, job_row, table_id=table_id, **kwargs) }}
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 782, in _invoke
mcritweb      |     rv = self._func(*arguments)
mcritweb      |   File "/opt/mcritweb/mcritweb/templates/table/table.html", line 13, in template
mcritweb      |     {{ row_macro(row_data, parent=table_id, **kwargs) }}
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 782, in _invoke
mcritweb      |     rv = self._func(*arguments)
mcritweb      |   File "/opt/mcritweb/mcritweb/templates/table/job_row.html", line 191, in template
mcritweb      |     <td job_id="{{ job.job_id }}" class="job-cell" valign="middle">{{ job_description(job, kwargs['families_by_id'], kwargs['samples_by_id']) }}</td>
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 782, in _invoke
mcritweb      |     rv = self._func(*arguments)
mcritweb      |   File "/opt/mcritweb/mcritweb/templates/table/job_row.html", line 17, in template
mcritweb      |     {% set sample_entry = samples_by_id.get(job.sample_id) %}
mcritweb      |   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 487, in getattr
mcritweb      |     return getattr(obj, attribute)
mcritweb      | jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'samples_by_id'`

And I've an error 500

**Comment by danielplohmann** [comment]
hey!

thanks for creating the issue!
I had a quick look and at least for me this was only affecting the progress view of the job.
So it's likely that all the matching jobs and the combination did actually run through.
You can check this on:
```
yourhost/data/jobs?active=combineMatchesToCross
```
your desired cross compare likely has a 100% there with the result button clickable.
I'll fix the issue with webUI at the next best chance for sure.

**Comment by sebdraven** [comment]
![image](https://github.com/danielplohmann/mcrit/assets/1478484/2b341db7-f3e9-42b2-8fd3-b25305c42d0f)
 It seems correct !

Could you confirm it's ok ?

**Comment by danielplohmann** [comment]
fixed with mcritweb 2025-01-21 v1.3.4
